spring:
  application:
    name: order-service
    
server:
  port: 8110
    
eureka:
  client:
    service-url: 
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2010/eureka
    
